uses: actions/checkout@v3
uses: Dylan700/sftp-upload-action@latest

with:
  server: ${{secrets.SFTP_SERVER}}
  username: ${{secrets.SFTP_USERNAME}}
  key: ${{secrets.KEY}}
  port: ${{secrets.SFTP_PORT}}
  uploads: |
    ./img/ => ./img/
    ./overview/ => ./overview_image/
