uses: actions/checkout@v3
uses: Dylan700/sftp-upload-action@latest

with:
  server: sftp.server.com
  username: jason-bourne
  key: ${{secrets.key}}
  passphrase: ${{secrets.passphrase}}
  port: 22
  uploads: |
    ./html/ => ./www/public_html/
    ./src/ => ./www/src/
